---
title: "multi_plot"
output: html_document
---


```{r}
library(DESeq2) # significance testing
library(ggplot2) # best plotting package
library(dplyr) # ggplot2 addon for better labels
library(cowplot)
library(magick)
library(here)
```


```{r}
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

#Get HS J2
```{r}
#VOLCANO PLOT FOR SENSE
df <- read.table("HS/DESeq2_senseunique_cleaned.txt", header=TRUE)

df$log2baseMean <- log(df$baseMean, 2)
df$shape <- ifelse(df$baseMean > 10000000, "triangle", "circle")
df$pval[df$padj<0.05] <- 0.05
df$shape[(abs(df$log2baseMean) > 1000000)] <- "triangle"


data <- df

  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))
  data$shape <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$shape, "star")
  data$color <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$color, "dsrna")
  
  # Color corresponds to fold change directionality
  hsj2 <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange, shape=shape)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.6, na.rm = T) + # add gene points
    xlim(4, 20) +
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    # ggtitle(label = "J2 Sense HS ") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange")) + # y-axis label
    #scale_x_continuous(expand = c(0, 0))#, limits = c(0, 15)) +
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "red", 
                                  "Untreated" = "#3182bd", 
                                  "dsrna" = "green",
                                  "none" = "#636363")) # change colors
  # Plot figure
  # colored

  
  file="HS/DESeq2_senseunique_cleaned_plot.png"
  

  ggsave(file=file, device = "png")
  dev.off()
  df = df[df$padj<0.05,]
  
  write.table(df, file = "test.csv", sep = "\t",row.names=FALSE,quote=TRUE)
  hsj2
```

#Get hsj2a
```{r}
  #VOLCANO PLOT FOR Antisense
  df <- read.table("HS/DESeq2_antisenseunique_cleaned.txt", header=TRUE)

  df$log2baseMean <- log(df$baseMean, 2)
df$shape <- ifelse(df$baseMean > 10000000, "triangle", "circle")
df$pval[df$padj<0.05] <- 0.05
df$shape[(abs(df$log2baseMean) > 1000000)] <- "triangle"
  
  
  data <- df
  
  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))
  data$shape <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$shape, "star")
  data$color <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$color, "dsrna")
  
  # Color corresponds to fold change directionality
  hsj2a <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange, shape=shape)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    xlim(4, 20) + 
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    # ggtitle(label = "J2 Anti-Sense HS ") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange")) + # y-axis label
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "red", 
                                  "Untreated" = "#3182bd", 
                                  "dsrna" = "green",
                                  "none" = "#636363")) # change colors
  # # Plot figure
  # colored
  
  # 

    
  file="HS/DESeq2_antisenseunique_cleaned_plot.png"
  

  ggsave(file=file, device = "png")
  
  dev.off()
  hsj2a
```

#Get okj2
```{r}

#VOLCANO PLOT FOR SENSE
df <- read.table("OK/DESeq2_senseunique_cleaned.txt", header=TRUE)

  df$log2baseMean <- log(df$baseMean, 2)
df$shape <- ifelse(df$baseMean > 10000000, "triangle", "circle")
df$pval[df$padj<0.05] <- 0.05
df$shape[(abs(df$log2baseMean) > 1000000)] <- "triangle"


data <- df

  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))
  data$shape <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$shape, "star")
  data$color <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$color, "dsrna")
  
  # Color corresponds to fold change directionality
  okj2 <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange, shape=shape)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    xlim(4, 20) +
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    # ggtitle(label = "J2 Sense \ntdp-1(ok803)") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange")) + # y-axis label
    #scale_x_continuous(expand = c(0, 0))#, limits = c(0, 15)) +
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "purple", 
                                  "Untreated" = "#3182bd", 
                                  "dsrna" = "green",
                                  "none" = "#636363")) # change colors
  # # Plot figure
  # colored

      
  file="OK/DESeq2_senseunique_cleaned_plot.png"

  ggsave(file=file, device = "png")
  dev.off()
  okj2

```

#Get okj2a
```{r}

  
  #VOLCANO PLOT FOR Antisense
  df <- read.table("OK/DESeq2_antisenseunique_cleaned.txt", header=TRUE)
  
  df$log2baseMean <- log(df$baseMean, 2)
df$shape <- ifelse(df$baseMean > 10000000, "triangle", "circle")
df$pval[df$padj<0.05] <- 0.05
df$shape[(abs(df$log2baseMean) > 1000000)] <- "triangle"
  
  
  data <- df
  
  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))
  data$shape <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$shape, "star")
  data$color <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$color, "dsrna")
  
  # Color corresponds to fold change directionality
  okj2a <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange, shape=shape)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    xlim(4, 20) +
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    # ggtitle(label = "J2 Anti-Sense \ntdp-1(ok803)") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange")) + # y-axis label
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "purple", 
                                  "Untreated" = "#3182bd", 
                                  "dsrna" = "green",
                                  "none" = "#636363")) # change colors
  okj2a
  # Plot figure
  # colored


        
  file="OK/DESeq2_antisenseunique_cleaned_plot.png"
  ggsave(file=file, device = "png")

  dev.off()
  okj2a 
  
```


######DSRNA Only
#Get dshsj2
```{r}
  #VOLCANO PLOT FOR SENSE dsRNA only
  df <- read.table("HS/DESeq2_senseunique_cleaned_dsRNAonly.txt", header=TRUE)

df$log2baseMean <- log(df$baseMean, 2)
df$shape <- ifelse(df$baseMean > 10000000, "triangle", "circle")
df$pval[df$padj<0.05] <- 0.05
df$shape[(abs(df$log2baseMean) > 1000000)] <- "triangle"


  
  data <- df
  
  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))
  data$shape <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$shape, "star")
  data$color <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$color, "dsrna")
  
  # Color corresponds to fold change directionality
  dshsj2 <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange, shape=shape)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    xlim(4, 20) +
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    # ggtitle(label = "J2 Sense HS dsRNA ") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange")) + # y-axis label
    #scale_x_continuous(expand = c(0, 0))#, limits = c(0, 15)) +
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "red", 
                                  "Untreated" = "#3182bd", 
                                  "dsrna" = "green",
                                  "none" = "#636363")) # change colors
  
  dshsj2
  # # Plot figure
  # colored
  # 
  dev.copy(png,filename="HS/DESeq2_senseunique_cleaned_dsRNAonly_basemean20_plot.png")
  dev.off()
  
  
```

#Get dshsj2a
```{r}

  #VOLCANO PLOT FOR Antisense dsRNA only
  df <- read.table("HS/DESeq2_antisenseunique_cleaned_dsRNAonly.txt", header=TRUE)
  

  df$log2baseMean <- log(df$baseMean, 2)
df$shape <- ifelse(df$baseMean > 10000000, "triangle", "circle")
df$pval[df$padj<0.05] <- 0.05
df$shape[(abs(df$log2baseMean) > 1000000)] <- "triangle"
  
  
  
  data <- df
  
  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))
  data$shape <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$shape, "star")
  data$color <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$color, "dsrna")
  
  # Color corresponds to fold change directionality
  dshsj2a <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange, shape=shape)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    xlim(4, 20) +
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    # ggtitle(label = "J2 Anti-Sense HS dsRNA ") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange")) + # y-axis label
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "red", 
                                  "Untreated" = "#3182bd", 
                                  "dsrna" = "green",
                                  "none" = "#636363")) # change colors
  # Plot figure
  # colored
  # 
  dshsj2a
  dev.copy(png,filename="HS/DESeq2_antisenseunique_cleaned_dsRNAonly_basemean20_plot.png")
  dev.off()
  # 
```

#dsokj2
```{r}
  #VOLCANO PLOT FOR SENSE dsRNA only
  df <- read.table("OK/DESeq2_senseunique_cleaned_dsRNAonly.txt", header=TRUE)
  
  df$log2baseMean <- log(df$baseMean, 2)
df$shape <- ifelse(df$baseMean > 10000000, "triangle", "circle")
df$pval[df$padj<0.05] <- 0.05
df$shape[(abs(df$log2baseMean) > 1000000)] <- "triangle"


  
  
  data <- df
  
  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))
  data$shape <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$shape, "star")
  data$color <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$color, "dsrna")
  
  # Color corresponds to fold change directionality
  dsokj2 <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange, shape=shape)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    # ggtitle(label = "J2 Sense \ntdp-1(ok803)") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange")) + # y-axis label
    #scale_x_continuous(expand = c(0, 0))#, limits = c(0, 15)) +
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "purple", 
                                  "Untreated" = "#3182bd", 
                                  "dsrna" = "green",
                                  "none" = "#636363")) # change colors
  dsokj2
  
  # Plot figure
  # colored
  # 
  dev.copy(png,filename="OK/DESeq2_senseunique_cleaned_dsRNAonly_basemean20_plot.png")
  dev.off()
  
  
```

#dsokj2a
```{r}

  
  #VOLCANO PLOT FOR Antisense dsRNA only
  df <- read.table("OK/DESeq2_antisenseunique_cleaned_dsRNAonly.txt", header=TRUE)
  
  df$log2baseMean <- log(df$baseMean, 2)
  df$shape <- ifelse(df$baseMean > 2000, "triangle", "circle")
  df$pval[df$padj<0.05] <- 0.05
  
  df$shape[(abs(df$baseMean) > 2000)] <- "triangle"
  df$baseMean[df$baseMean >  2000] <- 2000
  df$baseMean[df$baseMean < -2000] <- -2000
  
  
  data <- df
  
  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))
  data$shape <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$shape, "star")
  data$color <- ifelse(data$log2FoldChange_sig_and_sense_significant_and_antisense_significant == "False", data$color, "dsrna")
  
  # Color corresponds to fold change directionality
  dsokj2a <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange, shape=shape)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    # ggtitle(label = "J2 Anti-Sense \ntdp-1(ok803)") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange")) + # y-axis label
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "purple", 
                                  "Untreated" = "#3182bd", 
                                  "dsrna" = "green",
                                  "none" = "#636363")) # change colors
  # Plot figure
  # colored
  dsokj2a
  dev.copy(png,filename="OK/DESeq2_antisenseunique_cleaned_dsRNAonly_basemean20_plot.png")
  dev.off()
  
  
  
```



```{r}

# 
# "~/Google_Drive/Scripts/hs/worm/EMBO/writeup/Figures/fig4_J2_Enrichment/fig4.5_J2_Enrichment_GOTERM/SenseVenn.png"


SV <- ggdraw() + draw_image("fig4.5_J2_Enrichment_GOTERM/SenseVenn.png", scale = 0.9)
AV <- ggdraw() + draw_image("fig4.5_J2_Enrichment_GOTERM/AntisenseVenn.png", scale = 0.9)
```




```{r}

# 

plot2by2 <- plot_grid(hsj2, hsj2a,okj2, okj2a, SV, AV,
                      labels="AUTO", ncol = 2)
save_plot("MULTIPLOT_unique_cleaned_plot.png", plot2by2,
          ncol = 2, # we're saving a grid plot of 2 columns
          nrow = 3, # and 2 rows
          # each individual subplot should have an aspect ratio of 1.3
          base_aspect_ratio = 1.3
          )

```

```{r}
#Plots for masters defense

plot2by2 <- plot_grid(hsj2, hsj2a,dshsj2, dshsj2a,ncol = 2)
save_plot("MULTIPLOT_masters_heatshock.png", plot2by2,
          ncol = 2, # we're saving a grid plot of 2 columns
          nrow = 2, # and 2 rows
          # each individual subplot should have an aspect ratio of 1.3
          base_aspect_ratio = 1.3
          )

plot2by2 <- plot_grid(okj2, okj2a)
save_plot("MULTIPLOT_masters_ok_enrichment.png", plot2by2,
          ncol = 1, # we're saving a grid plot of 2 columns
          nrow = 1, # and 2 rows
          # each individual subplot should have an aspect ratio of 1.3
          base_aspect_ratio = 1.3
          )


plot2by2 <- plot_grid(hsj2, okj2)
save_plot("MULTIPLOT_masters_hs_ok_sense.png", plot2by2,
          ncol = 1, # we're saving a grid plot of 2 columns
          nrow = 1, # and 2 rows
          # each individual subplot should have an aspect ratio of 1.3
          base_aspect_ratio = 1.3
          )


plot2by2 <- plot_grid(hsj2a, okj2a)
save_plot("MULTIPLOT_masters_hs_ok_antisense.png", plot2by2,
          ncol = 1, # we're saving a grid plot of 2 columns
          nrow = 1, # and 2 rows
          # each individual subplot should have an aspect ratio of 1.3
          base_aspect_ratio = 1.3
          )

plot2by2 <- plot_grid(okj2, okj2a,dsokj2, dsokj2a,ncol = 2)
save_plot("MULTIPLOT_masters_OK.png", plot2by2,
          ncol = 2, # we're saving a grid plot of 2 columns
          nrow = 2, # and 2 rows
          # each individual subplot should have an aspect ratio of 1.3
          base_aspect_ratio = 1.3
          )

```



#Multiplot
```{r}
  
  
dev.off() 

#mp = multiplot(dshsj2, dshsj2a, cols=1)
#dev.copy(png,filename="ds_ONLY_MULTIPLOT_unique_cleaned_plot.png")

dev.off() 
  
  #PLOSONE
  #IMAGE HELP
  #https://danieljhocking.wordpress.com/2013/03/12/high-resolution-figures-in-r/
```

