---
title: "multi_plot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
library(DESeq2) # significance testing
library(ggplot2) # best plotting package
library(dplyr) # ggplot2 addon for better labels
library(cowplot)
```


```{r}
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)
  
  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)
  
  numPlots = length(plots)
  
  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                     ncol = cols, nrow = ceiling(numPlots/cols))
  }
  
  if (numPlots==1) {
    print(plots[[1]])
    
  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
    
    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
      
      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

#HS Sense
```{r}

#VOLCANO PLOT FOR SENSE

df <- read.table("unique_DOG/HS_combined_DOG_noOperon_unique_cleaned.csv", header=TRUE,sep=",")

df$log2baseMean <- log(df$baseMean, 2)
df$pval[df$padj<0.05] <- 0.05


data <- df

  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))
  
  # Color corresponds to fold change directionality
  hs <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    xlim(4.3, 20) +
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    ggtitle(label = "A") +  # add title
    # ggtitle(label = "J2 DOG HS") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange (HS / WT)")) + # y-axis label
    #scale_x_continuous(expand = c(0, 0))#, limits = c(0, 15)) +
    annotate("text",  x=Inf, y = Inf, label = "Heat shock DoG", vjust=1, hjust=1, size=5, fontface="bold") +
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "red", 
                                  "Untreated" = "#3182bd", 
                                  "none" = "#636363")) # change colors
  # Plot figure 
  hs
    file="unique_DOG/HS_combined_DOG_noOperon_unique_cleaned.csv_labels.png"
  ggsave(file=file, device = "png")
  dev.off()

```

#OK Sense
```{r}

#VOLCANO PLOT FOR SENSE
df <- read.table("unique_DOG/OK_combined_DOG_noOperon_unique_cleaned.csv", header=TRUE,sep=",")

df$log2baseMean <- log(df$baseMean, 2)

df$pval[df$padj<0.05] <- 0.05


data <- df

  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))

  
  # Color corresponds to fold change directionality
  ok <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    xlim(4.3, 20) +
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    # ggtitle(label = "J2 DOG tdp-1(ok803) ") +  # add title
    ggtitle(label = "B") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange (tdp-1 / WT)")) + # y-axis label
    #scale_x_continuous(expand = c(0, 0))#, limits = c(0, 15)) +
    annotate("text",  x=Inf, y = Inf, label = "tdp-1(ok803) DoG", vjust=1, hjust=1, size=5, fontface="bold") +
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "purple", 
                                  "Untreated" = "#3182bd", 
                                  "none" = "#636363")) # change colors
  # Plot figure

  ok
      file="unique_DOG/OK_combined_DOG_noOperon_unique_cleaned.csv_labels.png"
  ggsave(file=file, device = "png")
  dev.off()

  
```



#HS AntiSense
```{r}

#VOLCANO PLOT FOR SENSE

df <- read.table("unique_DOG/HS_combined_ADOG_noOperon_unique_cleaned.csv", header=TRUE,sep=",")

df$log2baseMean <- log(df$baseMean, 2)
df$pval[df$padj<0.05] <- 0.05


data <- df

  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))
  
  # Color corresponds to fold change directionality
  hsa <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    xlim(4.3, 20) +
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    ggtitle(label = "C") +  # add title
    # ggtitle(label = "J2 ADOG HS") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label
    ylab(expression("log2FoldChange (HS / WT)")) + # y-axis label
    annotate("text",  x=Inf, y = Inf, label = "Heat shock ADoG", vjust=1, hjust=1, size=5, fontface="bold") +
    #scale_x_continuous(expand = c(0, 0))#, limits = c(0, 15)) +
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "red", 
                                  "Untreated" = "#3182bd", 
                                  "none" = "#636363")) # change colors
  # Plot figure 
  hsa
    file="unique_DOG/HS_combined_ADOG_unique_cleaned_labelled.png"
  ggsave(file=file, device = "png")
  dev.off()

```






#OK Antisense
```{r}

#VOLCANO PLOT FOR SENSE
df <- read.table("unique_DOG/OK_combined_ADOG_noOperon_unique_cleaned.csv", header=TRUE,sep=",")

df$log2baseMean <- log(df$baseMean, 2)

df$pval[df$padj<0.05] <- 0.05


data <- df

  # Modify dataset to add new coloumn of colors
  data <- data %>%
    mutate(color = ifelse(data$log2FoldChange > 0 & data$padj < 0.05,
                          yes = "Treated",
                          no = ifelse(data$log2FoldChange < 0 & data$padj < 0.05, yes = "Untreated", no = "none") ))

  
  # Color corresponds to fold change directionality
  oka <- ggplot(data, aes(x = log2baseMean, y = log2FoldChange)) +
    geom_point(aes(color = factor(color)), size = 1.75, alpha = 0.8, na.rm = T) + # add gene points
    xlim(4.3, 20) +
    theme_bw(base_size = 15) + # clean up theme
    theme(legend.position = "none") + # remove legend 
    ggtitle(label = "D") +  # add title
    # ggtitle(label = "J2 ADOG tdp-1(ok803) ") +  # add title
    xlab(expression("log2baseMean")) + # x-axis label

    ylab(expression("log2FoldChange (tdp-1 / WT)")) + # y-axis label
    annotate("text",  x=Inf, y = Inf, label = "tdp-1(ok803) ADoG", vjust=1, hjust=1, size=5, fontface="bold") +
    
    
    geom_vline(xintercept = 0, colour = "black") + # add line at 0
    geom_hline(yintercept = 0, colour = "black") + # p(0.05) = 1.3
    scale_color_manual(values = c("Treated" = "purple", 
                                  "Untreated" = "#3182bd", 
                                  "none" = "#636363")) # change colors
  # Plot figure

  oka
      file="unique_DOG/OK_combined_ADOG_unique_cleaned.png"
  ggsave(file=file, device = "png")
  dev.off()

  
```





#Multiplot
```{r}


mp = multiplot(hs, hsa, ok, oka, cols=2)
  
# postscript(file="fig7_J2_Enrichment_DOG/DOG_ADOG_PLOT_noOperon.eps")

# dev.copy2eps(device=postscript,filename="~/Google_Drive/Scripts/hs/worm/EMBO/writeup/Figures/fig7_J2_Enrichment_DOG/DOG_ADOG_PLOT_noOperon.eps",out.type="eps")

dev.copy(png,filename="DOG_ADOG_PLOT_noOperon.png",width=1400, height=1800)

# postscript("Plot3.eps", width = 480, height = 480)
# plot(x, y) # Make plot
# dev.off()

#


dev.off() 

  
  #PLOSONE
  #IMAGE HELP
  #https://danieljhocking.wordpress.com/2013/03/12/high-resolution-figures-in-r/
```


```{r}
# mp = multiplot(ok, oka, cols=1)
# dev.copy(png,filename="DOG_OK_sense_antisense.png")
# 
# dev.off()
# mp = multiplot(hs, hsa, cols=1)
# dev.copy(png,filename="DOG_HS_sense_antisense.png")
# dev.off()

plot2by2 <- plot_grid(hs, ok,hsa, oka, ncol = 2)
save_plot("MULTIPLOT_unique_cleaned_plot.png", plot2by2,
          ncol = 2, # we're saving a grid plot of 2 columns
          nrow = 2, # and 2 rows
          # each individual subplot should have an aspect ratio of 1.3
          base_aspect_ratio = 1.3
          )



```

